-- A Project is a Workspace-owned human initiative that groups Productions.
-- Folder placement and Project membership remain independent dimensions.

CREATE TABLE public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    workspace_id bigint NOT NULL,
    folder_id bigint,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT projects_workspace_id_fkey
        FOREIGN KEY (workspace_id) REFERENCES public.workspaces(id) ON DELETE CASCADE,
    CONSTRAINT projects_folder_id_fkey
        FOREIGN KEY (folder_id) REFERENCES public.folders(id) ON DELETE SET NULL,
    CONSTRAINT projects_id_workspace_id_key UNIQUE (id, workspace_id)
);

CREATE INDEX projects_workspace_updated_idx
    ON public.projects (workspace_id, updated_at DESC, id);
CREATE INDEX projects_folder_idx
    ON public.projects (folder_id) WHERE folder_id IS NOT NULL;

ALTER TABLE public.productions ADD COLUMN project_id bigint;

ALTER TABLE public.productions
    ADD CONSTRAINT productions_project_workspace_id_fkey
    FOREIGN KEY (project_id, workspace_id)
    REFERENCES public.projects (id, workspace_id)
    ON DELETE SET NULL (project_id);

CREATE INDEX productions_project_idx
    ON public.productions (project_id) WHERE project_id IS NOT NULL;
