"""Versioned creative vocabulary for Stable Audio Sound Presets.

The frontend renders this data through the API.  Labels, education and model
phrasing therefore evolve without becoming component logic.
"""

from __future__ import annotations

from typing import Any


TAXONOMY_VERSION = "audio-taxonomy-v1"


def _item(identifier: str, category: str, label: str, prompt: str, *,
          definition: str, audible: str, use_when: str,
          aliases: tuple[str, ...] = (), models: tuple[str, ...] = (
              "small-music", "small-sfx"),
          contexts: tuple[str, ...] = (),
          conflicts: tuple[str, ...] = ()) -> dict[str, Any]:
    return {
        "id": identifier,
        "category": category,
        "labels": {"en": label},
        "help": {
            "definition_en": definition,
            "audible_effect_en": audible,
            "use_when_en": use_when,
        },
        "prompt_en": prompt,
        "aliases": list(aliases),
        "model_support": list(models),
        "suggestion_contexts": list(contexts),
        "conflicts_with": list(conflicts),
    }


M = ("small-music",)
S = ("small-sfx",)


ITEMS = (
    # Music production context. Context never implies genre.
    _item("context.story", "context", "Story / Narrative", "a story or narrative production",
          definition="Spoken or visual storytelling with a developing narrative.", audible="Suggestions favour emotional continuity and room for narration.", use_when="Use for fiction, audiobooks, bedtime stories or personal stories.", aliases=("story", "narrative", "audiobook"), models=M),
    _item("context.podcast", "context", "Podcast / Talk", "a podcast or talk production",
          definition="Conversation, interview or spoken commentary.", audible="Suggestions keep the music clear of the speaking voice.", use_when="Use for podcasts, interviews and talk formats.", aliases=("podcast", "talk", "interview"), models=M),
    _item("context.faith", "context", "Faith / Church", "a faith or church production",
          definition="Faith-centred spoken, ceremonial or community content.", audible="Suggestions can support reverence or gathering without choosing a genre for you.", use_when="Use for prayer, scripture, sermons and church moments.", aliases=("faith", "church", "prayer"), models=M),
    _item("context.documentary", "context", "Documentary", "a documentary production",
          definition="Factual narrative built from information, testimony or investigation.", audible="Suggestions support clarity, credibility and story tension.", use_when="Use for factual films, reports and investigative stories.", aliases=("documentary", "investigation"), models=M),
    _item("context.film", "context", "Video / Film", "a video or film production",
          definition="Picture-led content requiring a musical cue.", audible="Suggestions favour scene support and editorial pacing.", use_when="Use for films, episodes, trailers and general video.", aliases=("film", "video", "cinema"), models=M),
    _item("context.education", "context", "Education", "an educational production",
          definition="Material intended to explain, teach or guide.", audible="Suggestions favour clarity and sustained attention.", use_when="Use for courses, lessons and explainers.", aliases=("education", "course", "lesson"), models=M),
    _item("context.social", "context", "Social / Creator", "a social or creator production",
          definition="Short-form or personality-led creator content.", audible="Suggestions favour an immediate identity and clean edit points.", use_when="Use for reels, short videos and creator channels.", aliases=("social", "creator", "reel"), models=M),
    _item("context.wellness", "context", "Wellness", "a wellness production",
          definition="Guided rest, meditation or wellbeing content.", audible="Suggestions favour spacious, non-intrusive pacing.", use_when="Use for sleep, breathwork, meditation and gentle guidance.", aliases=("wellness", "meditation", "sleep"), models=M),
    _item("context.brand", "context", "Brand / Commercial", "a brand or commercial production",
          definition="Content expressing a product or brand identity.", audible="Suggestions favour memorable, concise musical identity.", use_when="Use for ads, product films and brand stories.", aliases=("brand", "commercial", "advert"), models=M),
    _item("context.gaming", "context", "Gaming", "a game production",
          definition="Interactive or game-related content.", audible="Suggestions support worlds, states and repeated listening.", use_when="Use for gameplay, game trailers and interactive scenes.", aliases=("game", "gaming"), models=M),
    _item("context.event", "context", "Event", "a live or recorded event",
          definition="A gathering with entrances, transitions or presentation moments.", audible="Suggestions favour clear cue roles and confident transitions.", use_when="Use for ceremonies, conferences and live programmes.", aliases=("event", "ceremony", "conference"), models=M),

    # Cue roles and moments.
    _item("cue.music_bed", "cue_role", "Music bed", "a continuous background music bed",
          definition="Music that supports a longer section without demanding attention.", audible="Steady, unobtrusive motion underneath the main content.", use_when="Use under narration, dialogue or a sustained scene.", aliases=("bed", "background music"), models=M),
    _item("cue.underscore", "cue_role", "Underscore", "an understated underscore",
          definition="Music closely supporting the emotion or meaning of a scene.", audible="The cue follows the emotional centre while staying secondary.", use_when="Use beneath story, testimony or documentary scenes.", aliases=("underscore",), models=M),
    _item("cue.transition", "cue_role", "Transition", "a concise transition cue",
          definition="Music that moves the production from one section to another.", audible="A clear change with an intentional edit point.", use_when="Use between chapters, segments or scenes.", aliases=("transition",), models=M),
    _item("cue.bumper", "cue_role", "Bumper", "a short branded bumper",
          definition="A short identifying cue around a segment.", audible="Immediate identity and a clean finish.", use_when="Use before or after recurring sections.", aliases=("bumper",), models=M),
    _item("cue.stinger", "cue_role", "Stinger", "a very short musical stinger",
          definition="A compact musical punctuation mark.", audible="Fast arrival and decisive landing.", use_when="Use for reveals, logos or editorial punctuation.", aliases=("stinger",), models=M),
    _item("cue.theme", "cue_role", "Theme / opener", "an opening theme",
          definition="A recognisable musical identity for the production.", audible="More memorable and foregrounded than a bed.", use_when="Use for openings, series identity and title sequences.", aliases=("theme", "opener"), models=M),
    _item("cue.build", "cue_role", "Build", "a cue that gradually builds",
          definition="Music that intentionally increases anticipation or scale.", audible="Increasing energy, density or intensity over time.", use_when="Use before a reveal, transition or climax.", aliases=("build", "riser"), models=M),
    _item("moment.reflection", "moment", "Personal reflection", "a personal reflective moment",
          definition="An inward-looking pause or testimony.", audible="Workspace, restraint and emotional intimacy.", use_when="Use when a speaker reflects or remembers.", aliases=("reflection", "reflective"), models=M),
    _item("moment.scripture", "moment", "Scripture reading", "a spoken scripture reading",
          definition="A passage of scripture read aloud.", audible="Room for language, with a respectful emotional frame.", use_when="Use underneath or around scripture.", aliases=("scripture", "bible reading"), models=M, contexts=("context.faith",)),
    _item("moment.prayer", "moment", "Prayer", "a spoken prayer",
          definition="A spoken prayer or devotional moment.", audible="Intimate support with minimal competition.", use_when="Use beneath prayer or quiet devotion.", aliases=("prayer",), models=M, contexts=("context.faith",)),
    _item("moment.testimony", "moment", "Testimony", "a personal testimony",
          definition="A first-person account of experience or change.", audible="Emotional support that can evolve with the story.", use_when="Use beneath personal faith or life stories.", aliases=("testimony",), models=M),
    _item("moment.suspense", "moment", "Suspense", "a suspenseful scene",
          definition="A scene built around uncertainty or anticipation.", audible="Controlled tension and withheld resolution.", use_when="Use for mystery, investigation or approaching danger.", aliases=("suspense", "mystery"), models=M),
    _item("moment.gathering", "moment", "Pre-service / gathering", "a welcoming pre-service gathering",
          definition="Music welcoming people before a shared event.", audible="Warm, social continuity with moderate presence.", use_when="Use before services, events or community gatherings.", aliases=("pre-service", "gathering"), models=M),

    # Voice and emotion.
    _item("voice.deep_background", "voice_relationship", "Deep background", "designed to remain deep beneath spoken voice",
          definition="Speech is unquestionably the focus.", audible="Very low musical competition and restrained movement.", use_when="Use for dense narration or intimate speech.", models=M),
    _item("voice.under_speech", "voice_relationship", "Under speech", "designed to remain beneath spoken narration",
          definition="Music supports speech while remaining clearly secondary.", audible="Background melody and controlled dynamics.", use_when="Use for normal voiceover and dialogue.", models=M),
    _item("voice.supportive", "voice_relationship", "Supportive", "supporting the spoken voice while remaining noticeable",
          definition="Music shares some emotional weight with speech.", audible="A present cue that still protects intelligibility.", use_when="Use when the music should help carry emotion.", models=M),
    _item("voice.balanced", "voice_relationship", "Balanced", "balanced with the spoken voice",
          definition="Speech and music have comparable narrative importance.", audible="More visible melody and movement.", use_when="Use for montage or sparse speech.", models=M),
    _item("voice.music_forward", "voice_relationship", "Music-forward", "music-forward in the production mix",
          definition="Music is a primary experience even if speech exists.", audible="Prominent arrangement and musical identity.", use_when="Use for openers, montages and sparse voice.", models=M),
    _item("speech.throughout", "speech_presence", "Speech throughout", "spoken voice throughout the cue",
          definition="Speech is present for most or all of the cue.", audible="The arrangement should consistently protect intelligibility.", use_when="Use for continuous narration, prayer or talk.", models=M),
    _item("speech.sections", "speech_presence", "Speech in sections", "spoken voice in parts of the cue",
          definition="Speech appears only during some sections.", audible="The music may open up between spoken passages.", use_when="Use for mixed narration and montage.", models=M),
    _item("speech.none", "speech_presence", "No speech", "no spoken voice",
          definition="No voice needs space in the mix.", audible="Music can carry more melody, density and dynamic range.", use_when="Use for purely musical scenes.", models=M),
    _item("energy.very_low", "energy", "Very low", "very low steady energy",
          definition="The cue remains extremely restrained.", audible="Little rhythmic or dynamic pressure.", use_when="Use for sleep, prayer and fragile reflection.", models=M),
    _item("energy.low", "energy", "Low", "low steady energy",
          definition="The cue moves gently without becoming static.", audible="Soft momentum and limited intensity.", use_when="Use for narration, reflection and calm guidance.", models=M),
    _item("energy.balanced", "energy", "Balanced", "balanced moderate energy",
          definition="Neither especially calm nor forceful.", audible="A natural middle level of motion.", use_when="Use for general background music.", models=M),
    _item("energy.high", "energy", "High", "high energetic momentum",
          definition="The cue feels active and forward-moving.", audible="More rhythm, attack and dynamic presence.", use_when="Use for action, celebration and foreground movement.", models=M),
    _item("energy.intense", "energy", "Intense", "intense sustained energy",
          definition="The cue operates near maximum force.", audible="Dense motion, pressure and strong impact.", use_when="Use for climaxes and extreme action.", models=M),
    _item("tension.peaceful", "tension", "Peaceful", "peaceful with no dramatic tension",
          definition="No meaningful sense of threat or instability.", audible="Stable harmony and relaxed pacing.", use_when="Use for reassurance, rest and warmth.", models=M),
    _item("tension.slight", "tension", "Slight tension", "a slight undercurrent of tension",
          definition="A small amount of uncertainty remains.", audible="Subtle friction without becoming threatening.", use_when="Use for curiosity and gentle anticipation.", models=M),
    _item("tension.uneasy", "tension", "Uneasy", "uneasy restrained tension",
          definition="The cue feels unsettled.", audible="Ambiguity, friction and withheld resolution.", use_when="Use for mystery and concern.", models=M),
    _item("tension.tense", "tension", "Tense", "clear sustained tension",
          definition="Pressure is a primary emotional quality.", audible="Tighter motion and persistent instability.", use_when="Use for suspense and conflict.", models=M),
    _item("tension.intense", "tension", "Intense", "extreme dramatic tension",
          definition="The cue communicates urgent danger or pressure.", audible="Strong friction, force and limited release.", use_when="Use for major threat or climax.", models=M),
    _item("arc.steady", "emotional_arc", "Stay steady", "maintains a steady emotional state",
          definition="The emotional direction does not substantially change.", audible="Consistent mood and scale.", use_when="Use for long beds and stable narration.", models=M),
    _item("arc.lift", "emotional_arc", "Gently lift", "gently becomes more uplifting",
          definition="The cue gradually gains hope or brightness.", audible="A subtle emotional rise rather than a dramatic build.", use_when="Use for encouragement and recovery.", models=M),
    _item("arc.soften", "emotional_arc", "Gently soften", "gradually softens",
          definition="The cue becomes calmer and less forceful.", audible="Reduced density, intensity or brightness.", use_when="Use for settling, closure and rest.", models=M),
    _item("arc.darker", "emotional_arc", "Become darker", "gradually becomes darker",
          definition="The emotional colour moves toward seriousness or threat.", audible="Growing ambiguity and tonal weight.", use_when="Use for reveals and approaching conflict.", models=M),
    _item("arc.peak_resolve", "emotional_arc", "Peak and resolve", "builds to a peak and then resolves",
          definition="The cue reaches a clear high point before settling.", audible="A complete dramatic arc.", use_when="Use for foreground narrative moments.", models=M),
    _item("mood.calm", "mood", "Calm", "calm",
          definition="Emotionally settled and unhurried.", audible="Smooth pacing with little agitation.", use_when="Use for rest, explanation or reassurance.", aliases=("peaceful", "serene"), models=M),
    _item("mood.reflective", "mood", "Reflective", "reflective",
          definition="Thoughtful and inward-looking.", audible="Measured phrasing and emotional space.", use_when="Use for memory, testimony and contemplation.", aliases=("thoughtful", "contemplative"), models=M),
    _item("mood.intimate", "mood", "Intimate", "intimate",
          definition="Close, personal and emotionally near.", audible="Small scale, detail and restrained performance.", use_when="Use for personal stories or quiet guidance.", models=M),
    _item("mood.warm", "mood", "Warm", "warm and human",
          definition="Welcoming, rounded and emotionally generous.", audible="Soft edges and comfortable tonal balance.", use_when="Use for family, community and reassurance.", models=M),
    _item("mood.hopeful", "mood", "Hopeful", "quietly hopeful",
          definition="A sense of possibility or gentle uplift.", audible="Subtle lift without necessarily becoming triumphant.", use_when="Use for recovery, encouragement or resolution.", models=M),
    _item("mood.reverent", "mood", "Reverent", "reverent",
          definition="Respectful and attentive to spiritual or ceremonial weight.", audible="Controlled performance with unhurried space.", use_when="Use for sacred, memorial or ceremonial moments.", models=M),
    _item("mood.joyful", "mood", "Joyful", "joyful",
          definition="Open positive emotion and delight.", audible="Brighter movement and energetic phrasing.", use_when="Use for celebration, play and positive arrival.", models=M),
    _item("mood.bittersweet", "mood", "Bittersweet", "bittersweet",
          definition="Warmth and sadness held together.", audible="Emotional ambiguity rather than a purely happy or sad tone.", use_when="Use for memory, farewell or tender change.", models=M),
    _item("mood.sad", "mood", "Sad", "sad and tender",
          definition="Grief, loss or emotional heaviness.", audible="Slower movement and restrained brightness.", use_when="Use for loss, mourning or vulnerability.", models=M),
    _item("mood.mysterious", "mood", "Mysterious", "mysterious",
          definition="Unclear, hidden or intriguing.", audible="Ambiguous harmony and withheld resolution.", use_when="Use for discovery, secrets or questions.", models=M),
    _item("mood.tense", "mood", "Tense", "tense",
          definition="Pressure, danger or unresolved anticipation.", audible="Tighter rhythm, friction and reduced release.", use_when="Use for suspense, urgency or conflict.", conflicts=("arrangement.dynamics_restrained",), models=M),
    _item("mood.dreamlike", "mood", "Dreamlike", "dreamlike and floating",
          definition="Unreal, hazy or suspended.", audible="Soft transitions and diffuse space.", use_when="Use for sleep, memory or surreal scenes.", models=M),
    _item("mood.playful", "mood", "Playful", "playful",
          definition="Light, curious and mischievous.", audible="Bouncy gestures and surprising details.", use_when="Use for children, comedy and discovery.", models=M),

    # Musical world.
    _item("genre.ambient", "genre", "Ambient", "Ambient",
          definition="Texture-led music with spacious development.", audible="Sustained layers and slow change.", use_when="Use for beds, atmosphere and contemplation.", aliases=("atmospheric",), models=M),
    _item("genre.neo_classical", "genre", "Neo-classical", "Neo-Classical",
          definition="Contemporary music using classical instruments and restraint.", audible="Piano and strings with modern intimate production.", use_when="Use for reflection, stories and emotional documentary.", aliases=("neoclassical",), models=M),
    _item("genre.cinematic", "genre", "Cinematic", "Cinematic Score",
          definition="Music shaped like a screen score.", audible="Clear arcs, scale and scene-driven emotion.", use_when="Use for film, trailers and dramatic story.", models=M),
    _item("genre.spiritual_ambient", "genre", "Spiritual ambient", "Spiritual Ambient",
          definition="Ambient music with contemplative sacred character.", audible="Open, spacious and meditative layers.", use_when="Use for prayer or spiritual reflection without implying gospel.", models=M),
    _item("genre.gospel", "genre", "Contemporary gospel", "Contemporary Gospel",
          definition="Modern gospel-influenced instrumental language.", audible="Soulful harmony, groove and church-rooted instrumentation.", use_when="Choose explicitly when gospel is the desired style.", models=M),
    _item("genre.neo_soul", "genre", "Neo-soul", "Neo-Soul",
          definition="Modern soul harmony with relaxed groove.", audible="Rich chords, warm bass and laid-back pocket.", use_when="Use for sophisticated warmth and human groove.", models=M),
    _item("genre.acoustic_folk", "genre", "Acoustic folk", "Acoustic Folk",
          definition="Organic song-like language built around acoustic instruments.", audible="Guitar, strings and natural room presence.", use_when="Use for human, grounded stories.", models=M),
    _item("genre.jazz", "genre", "Jazz", "Jazz",
          definition="Improvisational harmony and rhythmic language.", audible="Expressive phrasing, swing or sophisticated harmony.", use_when="Use when jazz is an explicit creative direction.", models=M),
    _item("genre.alternative_rock", "genre", "Alternative rock", "Alternative Rock",
          definition="Guitar-led rock with modern or independent character.", audible="Drums, bass and electric guitars with strong energy.", use_when="Use for force, youth or live-band identity.", models=M),
    _item("genre.electronic", "genre", "Electronic", "Electronic",
          definition="Music built primarily from synthesis and electronic production.", audible="Synthetic timbre, programmed rhythm and precise texture.", use_when="Use for technology, motion and modern worlds.", models=M),
    _item("genre.lofi", "genre", "Lo-fi", "Lo-Fi",
          definition="Intentionally imperfect, softened production.", audible="Dust, saturation and relaxed detail.", use_when="Use for casual, nostalgic or intimate beds.", models=M),
    _item("genre.minimal", "genre", "Minimal score", "Minimal Score",
          definition="Score language reduced to a few essential elements.", audible="Repetition, space and controlled development.", use_when="Use under dialogue or focused tension.", models=M),
    _item("harmony.major", "harmonic_feel", "Bright / major", "bright major harmony",
          definition="Harmony centred on a clear, positive major quality.", audible="Open brightness and stable uplift.", use_when="Use for confidence, welcome or celebration.", models=M),
    _item("harmony.minor", "harmonic_feel", "Introspective / minor", "introspective minor harmony",
          definition="Harmony centred on a reflective minor quality.", audible="Depth, seriousness or tenderness.", use_when="Use for reflection, sadness or tension.", models=M),
    _item("harmony.suspended", "harmonic_feel", "Open / suspended", "open suspended harmony",
          definition="Chords avoid a firm major/minor resolution.", audible="Air, ambiguity and gentle anticipation.", use_when="Use for prayer, wonder or unresolved reflection.", models=M),
    _item("harmony.consonant", "harmonic_feel", "Warm / consonant", "warm consonant harmony",
          definition="Smooth harmony with little friction.", audible="Comfort and stable emotional support.", use_when="Use for reassurance and welcoming content.", models=M),
    _item("harmony.bittersweet", "harmonic_feel", "Bittersweet", "bittersweet harmony",
          definition="Harmony combining warmth with emotional ache.", audible="Tender ambiguity and memory.", use_when="Use for farewell, change or nostalgia.", models=M),
    _item("rhythm.free_time", "rhythm_groove", "Free time", "free-time pacing",
          definition="No strict audible pulse.", audible="Phrases breathe independently of a beat.", use_when="Use for intimate, ambient or reflective music.", models=M),
    _item("rhythm.steady_pulse", "rhythm_groove", "Subtle steady pulse", "a subtle steady pulse",
          definition="A consistent pulse without a strong drum groove.", audible="Gentle forward motion.", use_when="Use to maintain momentum under speech.", models=M),
    _item("rhythm.relaxed_pocket", "rhythm_groove", "Relaxed pocket", "a relaxed pocket groove",
          definition="A laid-back but clearly felt groove.", audible="Human swing and comfortable momentum.", use_when="Use for soul, gospel and warm gathering music.", models=M),
    _item("pace.very_slow", "pace", "Very slow", "very slow pacing",
          definition="The cue moves at a very slow perceived tempo.", audible="Long phrases and abundant time between events.", use_when="Use for prayer, sleep and deep reflection.", models=M),
    _item("pace.slow", "pace", "Slow", "slow pacing",
          definition="A clearly relaxed tempo.", audible="Unhurried motion with room to breathe.", use_when="Use for narration and reflective material.", models=M),
    _item("pace.relaxed", "pace", "Relaxed", "relaxed mid-slow pacing",
          definition="Comfortable forward motion without urgency.", audible="A gentle pulse and natural flow.", use_when="Use for warm background music.", models=M),
    _item("pace.moderate", "pace", "Moderate", "moderate pacing",
          definition="A neutral mid-tempo feel.", audible="Balanced motion and energy.", use_when="Use for general production music.", models=M),
    _item("pace.fast", "pace", "Fast", "fast pacing",
          definition="A quick perceived tempo.", audible="Immediate momentum and shorter gestures.", use_when="Use for action, urgency or lively content.", models=M),

    # Instruments and modifiers.
    _item("instrument.felt_piano", "instrument", "Felt piano", "Felt Piano",
          definition="Piano recorded with felt softening the hammer attack.", audible="Intimate, muted and delicate notes.", use_when="Use for reflection, sleep and emotional narration.", aliases=("soft piano",), models=M),
    _item("instrument.grand_piano", "instrument", "Grand piano", "Grand Piano",
          definition="Full-range acoustic concert piano.", audible="Clear attack, resonance and dynamic range.", use_when="Use for expressive foreground piano.", aliases=("piano",), models=M),
    _item("instrument.cello", "instrument", "Cello", "Cello",
          definition="Low bowed string instrument with a human vocal range.", audible="Warm sustained lines and emotional weight.", use_when="Use for intimacy, sadness or depth.", models=M),
    _item("instrument.bowed_strings", "instrument", "Bowed strings", "Bowed Strings",
          definition="A string section or layered bowed instruments.", audible="Sustained harmonic movement and emotional breadth.", use_when="Use for cinematic support and gradual swells.", models=M),
    _item("instrument.synth_pad", "instrument", "Warm synth pad", "Warm Synth Pad",
          definition="A sustained synthesizer layer with soft edges.", audible="Continuous warmth and atmospheric support.", use_when="Use for beds, ambience and harmonic glue.", models=M),
    _item("instrument.acoustic_guitar", "instrument", "Acoustic guitar", "Acoustic Guitar",
          definition="Steel- or nylon-string acoustic guitar.", audible="Organic plucked rhythm and human closeness.", use_when="Use for folk, lifestyle and grounded stories.", models=M),
    _item("instrument.electric_guitar", "instrument", "Electric guitar", "Electric Guitar",
          definition="Amplified guitar with a wide range of tones.", audible="From clean texture to aggressive drive.", use_when="Use for rock, ambient texture or bold identity.", models=M),
    _item("instrument.rhodes", "instrument", "Rhodes", "Rhodes Electric Piano",
          definition="Warm tine-based electric piano.", audible="Rounded chords with soft bell-like attack.", use_when="Use for soul, jazz and relaxed groove.", models=M),
    _item("instrument.hammond", "instrument", "Hammond organ", "Hammond Organ",
          definition="Tonewheel organ associated with gospel, soul and rock.", audible="Warm sustained chords and expressive movement.", use_when="Use when organ colour is explicitly wanted.", models=M),
    _item("instrument.electric_bass", "instrument", "Electric bass", "Electric Bass",
          definition="Amplified bass guitar.", audible="Round low-end pulse and groove foundation.", use_when="Use for band-based and groove-led music.", models=M),
    _item("instrument.light_drums", "instrument", "Light drums", "Soft Drums",
          definition="A restrained acoustic or hybrid drum part.", audible="Gentle pulse without dominating the mix.", use_when="Use when speech needs subtle rhythmic support.", models=M),
    _item("instrument.low_strings", "instrument", "Low strings", "Low Strings",
          definition="Cellos and basses focused in the lower register.", audible="Dark weight and restrained tension.", use_when="Use for suspense or solemn depth.", models=M),
    _item("modifier.sparse", "instrument_modifier", "Sparse notes", "sparse notes",
          definition="The instrument plays only occasional notes.", audible="More silence and separation around each gesture.", use_when="Use to leave room for speech or emotion.", models=M),
    _item("modifier.soft_attack", "instrument_modifier", "Soft attack", "soft attacks",
          definition="Notes begin gently rather than sharply.", audible="Reduced transient competition and a tender entrance.", use_when="Use under speech or for intimate material.", models=M),
    _item("modifier.legato", "instrument_modifier", "Legato", "legato phrasing",
          definition="Notes connect smoothly without obvious gaps.", audible="Long flowing lines.", use_when="Use for lyrical, calm or emotional performance.", models=M),
    _item("modifier.sustained", "instrument_modifier", "Sustained", "long sustained tones",
          definition="Notes are held for a long time.", audible="Continuous support and slow movement.", use_when="Use for pads, strings and spacious beds.", models=M),
    _item("modifier.gentle", "instrument_modifier", "Gentle", "gentle performance",
          definition="Played with restraint and little force.", audible="Softer dynamics and fewer aggressive transients.", use_when="Use for calm, intimate or spoken-word work.", models=M),
    _item("modifier.close_miked", "instrument_modifier", "Close-miked", "close-miked recording",
          definition="The microphone is positioned close to the instrument.", audible="Detailed, intimate sound with less room.", use_when="Use when the performance should feel near.", models=M),
    _item("modifier.pizzicato", "instrument_modifier", "Pizzicato", "pizzicato plucking",
          definition="String players pluck instead of bowing.", audible="Short, precise and often playful notes.", use_when="Use for light rhythm, tension ticks or playful movement.", models=M),

    # Arrangement values.
    _item("arrangement.density_sparse", "arrangement_density", "Very sparse", "very sparse arrangement",
          definition="Only a few elements play at once.", audible="Clear separation and abundant room.", use_when="Use beneath speech or for intimate cues.", conflicts=("arrangement.density_dense",), models=M),
    _item("arrangement.density_balanced", "arrangement_density", "Balanced", "balanced arrangement density",
          definition="A moderate number of elements share the arrangement.", audible="Full enough to engage without feeling crowded.", use_when="Use for general background and scene music.", models=M),
    _item("arrangement.density_dense", "arrangement_density", "Dense", "dense layered arrangement",
          definition="Many elements play together.", audible="Full, rich and attention-grabbing texture.", use_when="Use for foreground or climactic music.", conflicts=("arrangement.density_sparse",), models=M),
    _item("arrangement.melody_minimal", "melody_prominence", "Almost none", "minimal melodic activity",
          definition="No clearly dominant tune.", audible="Texture and harmony lead instead of melody.", use_when="Use under dense speech.", models=M),
    _item("arrangement.melody_background", "melody_prominence", "Background", "background-level melody",
          definition="A melody exists but remains secondary.", audible="Recognisable shape without pulling focus.", use_when="Use for normal narration beds.", models=M),
    _item("arrangement.melody_lead", "melody_prominence", "Lead", "prominent lead melody",
          definition="The melody is a primary feature.", audible="A memorable line that commands attention.", use_when="Use for themes and music-forward moments.", models=M),
    _item("arrangement.percussion_none", "percussion_presence", "None", "no percussion",
          definition="No drums or percussion are requested.", audible="Free, soft pacing without rhythmic attacks.", use_when="Use for prayer, reflection and intimate narration.", models=M),
    _item("arrangement.percussion_light", "percussion_presence", "Light", "light restrained percussion",
          definition="Percussion is present but restrained.", audible="Gentle pulse with limited transients.", use_when="Use for motion that still protects speech.", models=M),
    _item("arrangement.percussion_heavy", "percussion_presence", "Heavy", "heavy prominent percussion",
          definition="Drums are a major feature.", audible="Strong rhythm and physical impact.", use_when="Use for energetic, foreground music.", models=M),
    _item("arrangement.dynamics_restrained", "dynamics", "Very restrained", "very restrained dynamics",
          definition="Volume and intensity change only slightly.", audible="Stable support without dramatic swells.", use_when="Use beneath speech or for calm continuity.", conflicts=("arrangement.dynamics_dramatic", "mood.tense"), models=M),
    _item("arrangement.dynamics_natural", "dynamics", "Natural", "natural dynamic movement",
          definition="Moderate organic changes in intensity.", audible="The cue breathes without becoming theatrical.", use_when="Use for story and general background music.", models=M),
    _item("arrangement.dynamics_dramatic", "dynamics", "Dramatic", "dramatic dynamic swells",
          definition="Large changes in intensity and scale.", audible="Strong builds, drops and emotional peaks.", use_when="Use for foreground drama or climaxes.", conflicts=("arrangement.dynamics_restrained",), models=M),
    _item("arrangement.evolution_static", "evolution", "Mostly static", "mostly static development",
          definition="The musical material changes very little.", audible="Consistent texture over time.", use_when="Use for long, stable beds.", models=M),
    _item("arrangement.evolution_slow", "evolution", "Slowly evolving", "slow gradual evolution",
          definition="Changes arrive gradually.", audible="Subtle development without sudden events.", use_when="Use for narration, meditation and documentary beds.", models=M),
    _item("arrangement.evolution_strong", "evolution", "Strong development", "strong musical development",
          definition="The cue noticeably changes sections or intensity.", audible="Clear progression and transformation.", use_when="Use for montage and foreground arcs.", models=M),
    _item("arrangement.phrase_space", "phrase_space", "Lots of space", "generous space between phrases",
          definition="Musical gestures leave frequent gaps.", audible="Breathing room for words and emotional landings.", use_when="Use under speech or in intimate cues.", models=M),
    _item("arrangement.phrase_continuous", "phrase_space", "Continuous", "continuous musical phrasing",
          definition="Few gaps between musical gestures.", audible="A sustained, connected flow.", use_when="Use for ambience or music-forward movement.", models=M),
    _item("arrangement.rhythm_still", "rhythmic_activity", "Still", "almost no rhythmic activity",
          definition="Very little audible rhythmic motion.", audible="Floating or static texture.", use_when="Use for sleep, prayer and deep ambience.", models=M),
    _item("arrangement.rhythm_gentle", "rhythmic_activity", "Gentle", "gentle rhythmic activity",
          definition="Small rhythmic gestures provide motion.", audible="Subtle pulse without a driving groove.", use_when="Use under speech.", models=M),
    _item("arrangement.rhythm_driving", "rhythmic_activity", "Driving", "driving rhythmic activity",
          definition="Rhythm strongly propels the cue.", audible="Persistent forward momentum.", use_when="Use for action and music-forward scenes.", models=M),
    _item("arrangement.harmony_slow", "harmonic_movement", "Very slow", "very slow harmonic movement",
          definition="Chords change infrequently.", audible="Stability and long emotional space.", use_when="Use for narration and ambience.", models=M),
    _item("arrangement.harmony_moderate", "harmonic_movement", "Moderate", "moderate harmonic movement",
          definition="Chords change at a natural middle pace.", audible="Balanced development without restlessness.", use_when="Use for general story and background music.", models=M),
    _item("arrangement.harmony_frequent", "harmonic_movement", "Frequent", "frequent harmonic movement",
          definition="Chords change often.", audible="More active emotional and musical motion.", use_when="Use for foreground or sophisticated cues.", models=M),
    _item("arrangement.low_light", "low_end_weight", "Light", "light restrained low end",
          definition="Bass weight remains limited.", audible="Airy, less physically heavy production.", use_when="Use for delicate speech beds.", models=M),
    _item("arrangement.low_balanced", "low_end_weight", "Balanced", "balanced low-end weight",
          definition="Bass supports without dominating.", audible="Natural body and stability.", use_when="Use for most production music.", models=M),
    _item("arrangement.low_heavy", "low_end_weight", "Weighty", "weighty prominent low end",
          definition="Bass is physically prominent.", audible="More power and scale.", use_when="Use for impact and music-forward cues.", models=M),

    # Project and cue behaviour.
    _item("production.warm", "production_character", "Warm", "warm production with rounded transients and softened high frequencies",
          definition="A rounded tonal character without harsh brightness.", audible="Soft edges and comfortable body.", use_when="Use for intimacy, narration and human warmth.", models=M),
    _item("production.organic", "production_character", "Organic", "organic production",
          definition="Natural, human and acoustic character.", audible="Less synthetic precision and more physical texture.", use_when="Use for grounded or intimate work.", models=M),
    _item("production.clean", "production_character", "Clean", "clean production",
          definition="Clear and controlled without obvious grit.", audible="Defined detail and low noise.", use_when="Use for modern, professional clarity.", models=M),
    _item("production.analog", "production_character", "Analog", "subtle analog character",
          definition="Tape or hardware-inspired colour.", audible="Gentle saturation and softened transients.", use_when="Use for warmth, nostalgia or cohesion.", models=M),
    _item("production.lofi", "production_character", "Lo-fi", "lo-fi production character",
          definition="Intentional imperfection and limited fidelity.", audible="Dust, wobble or softened bandwidth.", use_when="Use for nostalgia or casual intimacy.", models=M),
    _item("production.airy", "production_character", "Airy", "airy open production",
          definition="Light, open high-frequency character.", audible="Breath, openness and reduced weight.", use_when="Use for calm, dreamlike or spacious cues.", models=M),
    _item("production.dark", "production_character", "Dark", "dark softened tonal balance",
          definition="Reduced brightness with stronger low-mid focus.", audible="Weight, mystery and less sparkle.", use_when="Use for tension, seriousness or night scenes.", models=M),
    _item("palette.acoustic", "production_palette", "Acoustic", "primarily acoustic instrumentation and production",
          definition="The sound world is built from physical instruments.", audible="Organic transients, room and human variation.", use_when="Use for grounded, intimate or traditional colour.", models=M),
    _item("palette.hybrid", "production_palette", "Hybrid", "a hybrid acoustic and electronic palette",
          definition="Acoustic and electronic sources share the production.", audible="Organic detail with synthetic support.", use_when="Use for contemporary cinematic and flexible beds.", models=M),
    _item("palette.electronic", "production_palette", "Electronic", "primarily electronic instrumentation and production",
          definition="Synthesis and programmed sources dominate.", audible="Precise, designed and synthetic colour.", use_when="Use for technology and modern production worlds.", models=M),
    _item("tone.dark", "production_tone", "Dark", "dark tonal balance",
          definition="High frequencies are restrained.", audible="More weight and less sparkle.", use_when="Use for seriousness or mystery.", models=M),
    _item("tone.balanced", "production_tone", "Balanced", "balanced tonal character",
          definition="No strong bias toward darkness or brightness.", audible="Natural full-range presentation.", use_when="Use for general production music.", models=M),
    _item("tone.bright", "production_tone", "Bright", "bright clear tonal character",
          definition="High-frequency clarity is prominent.", audible="Sparkle, air and immediacy.", use_when="Use for uplift and clean modern identity.", models=M),
    _item("recording.dry", "recording_character", "Dry", "dry recording with minimal reverb",
          definition="Very little room or reverberation is audible.", audible="Direct, controlled and close sound.", use_when="Use for clarity and later mixing flexibility.", models=M),
    _item("recording.wide", "recording_character", "Wide stereo", "wide stereo recording",
          definition="The production spans a broad stereo image.", audible="Large left-right width.", use_when="Use for immersive or music-forward material.", models=M),
    _item("recording.tape", "recording_character", "Tape-recorded", "tape-recorded character",
          definition="The recording carries tape-like colour.", audible="Soft saturation, cohesion and slight imperfection.", use_when="Use for warmth and nostalgia.", models=M),
    _item("loop.seamless", "loop_intention", "Designed to loop", "designed to continue naturally for looping",
          definition="The musical ending should avoid an obvious final cadence.", audible="A continuation-friendly final section.", use_when="Use for beds and repeated playback; final seamlessness still needs editing.", models=M),
    _item("loop.none", "loop_intention", "No loop needed", "a complete standalone cue",
          definition="The cue does not need to repeat.", audible="A normal beginning and ending are acceptable.", use_when="Use for one-off scenes and fixed edits.", models=M),
    _item("space.close", "workspace", "Close & intimate", "close intimate room character",
          definition="The sound feels physically near.", audible="Detail with little reverberant distance.", use_when="Use for personal and quiet material.", models=M),
    _item("space.natural", "workspace", "Natural room", "natural room ambience",
          definition="A believable moderate acoustic space.", audible="Realistic depth without obvious large reverb.", use_when="Use for organic general-purpose production.", models=M),
    _item("space.spacious", "workspace", "Spacious", "natural spaciousness",
          definition="A broad sense of air and distance.", audible="Longer tails and wider perceived space.", use_when="Use for ambient, sacred or cinematic cues.", models=M),
    _item("space.huge", "workspace", "Huge", "a huge reverberant space",
          definition="An intentionally very large acoustic environment.", audible="Long, dramatic reverberation and scale.", use_when="Use for awe, monuments and foreground drama.", models=M),
    _item("ending.natural", "ending", "Natural", "a natural ending",
          definition="The cue concludes without a special final gesture.", audible="A believable musical finish.", use_when="Use when no precise editorial ending is required.", models=M),
    _item("ending.soft", "ending", "Soft resolution", "a soft resolved ending",
          definition="The cue settles gently into resolution.", audible="A quiet, emotionally complete landing.", use_when="Use after prayer, reflection or calm narration.", models=M),
    _item("ending.strong", "ending", "Strong ending", "a strong decisive ending",
          definition="The cue finishes with clear emphasis.", audible="A confident final hit or cadence.", use_when="Use for bumpers, reveals and foreground cues.", models=M),
    _item("ending.continue", "ending", "Continue naturally", "continues naturally without a final cadence",
          definition="The cue feels as if it could continue beyond the file.", audible="No pronounced final resolution.", use_when="Use for loops, edits and beds.", models=M),
    _item("constraint.no_vocals", "constraint", "No vocals", "purely instrumental with no vocal-like textures",
          definition="Avoid vocal or choir-like material.", audible="Instrumental texture only.", use_when="Use whenever voice-like sounds would compete with speech.", models=M),
    _item("constraint.no_drama", "constraint", "No dramatic rises", "steady restrained dynamics without dramatic rises",
          definition="Avoid sudden builds and theatrical swells.", audible="Stable, predictable support.", use_when="Use for long narration and calm beds.", models=M),
    _item("constraint.no_busy_melody", "constraint", "No busy melody", "low melodic prominence with simple spacious phrasing",
          definition="Avoid dense or attention-seeking melodic motion.", audible="More room for speech and fewer competing notes.", use_when="Use beneath dialogue or narration.", models=M),

    # SFX taxonomy.
    _item("sfx.family.foley", "sfx_family", "Foley", "foley sound effect",
          definition="A physical everyday action recorded as a production sound.", audible="Tactile, realistic detail.", use_when="Use for footsteps, handling and object interaction.", models=S),
    _item("sfx.family.ambience", "sfx_family", "Ambience", "continuous environmental ambience",
          definition="A sustained environmental sound bed.", audible="Continuous place and atmosphere rather than one event.", use_when="Use for rooms, weather, crowds and location tone.", models=S),
    _item("sfx.family.impact", "sfx_family", "Impact", "impact sound effect",
          definition="A short collision or hit.", audible="A defined transient and decay.", use_when="Use for doors, hits, drops and editorial emphasis.", models=S),
    _item("sfx.family.transition", "sfx_family", "Transition", "transition sound effect",
          definition="A sound designed to move between moments.", audible="Directional motion, rise, fall or sweep.", use_when="Use for scene and interface transitions.", models=S),
    _item("sfx.material.wood", "sfx_material", "Wood", "wooden material",
          definition="A source made primarily from wood.", audible="Warm, hollow or dense resonances depending on size.", use_when="Use for doors, furniture and wooden objects.", models=S),
    _item("sfx.material.metal", "sfx_material", "Metal", "metallic material",
          definition="A source made primarily from metal.", audible="Bright resonance, ring or clang.", use_when="Use for tools, machinery and metallic objects.", models=S),
    _item("sfx.material.glass", "sfx_material", "Glass", "glass material",
          definition="A rigid glass source.", audible="Bright, fragile ringing and sharp transients.", use_when="Use for bottles, windows and glass objects.", models=S),
    _item("sfx.material.fabric", "sfx_material", "Fabric", "fabric material",
          definition="Cloth or textile movement.", audible="Soft friction with little resonance.", use_when="Use for clothing, sheets and soft handling.", models=S),
    _item("sfx.action.close", "sfx_action", "Closes", "closing",
          definition="The source moves into a closed position.", audible="A movement followed by a final contact.", use_when="Use for doors, lids and containers.", models=S),
    _item("sfx.action.slam", "sfx_action", "Slams shut", "slamming shut",
          definition="A fast, forceful closing action.", audible="Strong impact with a short aggressive transient.", use_when="Use when weight or urgency matters.", models=S),
    _item("sfx.action.drop", "sfx_action", "Drops", "dropping and impacting",
          definition="The source falls and hits a surface.", audible="Falling motion followed by impact and possible bounce.", use_when="Use for object falls.", models=S),
    _item("sfx.action.scrape", "sfx_action", "Scrapes", "scraping across a surface",
          definition="The source drags against another surface.", audible="Continuous friction with material detail.", use_when="Use for furniture, tools and abrasive motion.", models=S),
    _item("sfx.action.rain", "sfx_action", "Falls steadily", "falling steadily",
          definition="A continuous repeated falling action.", audible="Sustained varied droplets or particles.", use_when="Use for rain or granular ambience.", models=S),
    _item("sfx.perspective.close", "sfx_perspective", "Close", "close listening perspective",
          definition="The listener is near the source.", audible="Strong detail and direct sound.", use_when="Use for tactile foreground effects.", models=S),
    _item("sfx.perspective.medium", "sfx_perspective", "A few metres away", "a few metres away",
          definition="The source sits at a believable middle distance.", audible="Balanced direct sound and environment.", use_when="Use for normal scene placement.", models=S),
    _item("sfx.perspective.distant", "sfx_perspective", "Distant", "distant listening perspective",
          definition="The source is far from the listener.", audible="Less detail and more environmental filtering.", use_when="Use for off-screen or background events.", models=S),
    _item("sfx.motion.static", "sfx_motion", "Stationary", "stationary in one position",
          definition="The source does not move through the scene.", audible="Stable position and perspective.", use_when="Use for fixed machinery, ambience or one-place events.", models=S),
    _item("sfx.motion.approach", "sfx_motion", "Approaches", "approaching the listener",
          definition="The source moves toward the listener.", audible="Growing level and proximity.", use_when="Use for vehicles, footsteps and moving objects.", models=S),
    _item("sfx.motion.pass", "sfx_motion", "Passes by", "passing by the listener",
          definition="The source moves across and beyond the listener.", audible="A clear approach, closest point and departure.", use_when="Use for vehicles and fast moving objects.", models=S),
    _item("sfx.intensity.light", "sfx_intensity", "Light", "light intensity",
          definition="The event has little force.", audible="Soft level and restrained transient.", use_when="Use for gentle handling and subtle ambience.", models=S),
    _item("sfx.intensity.medium", "sfx_intensity", "Medium", "moderate intensity",
          definition="A natural middle level of force.", audible="Clear event without exaggeration.", use_when="Use for ordinary realistic action.", models=S),
    _item("sfx.intensity.heavy", "sfx_intensity", "Heavy", "heavy forceful intensity",
          definition="The event carries substantial force.", audible="Strong transient and physical weight.", use_when="Use for slams, impacts and large objects.", models=S),
    _item("sfx.realism.realistic", "sfx_realism", "Realistic", "realistic natural recording",
          definition="The sound should be believable as a real recording.", audible="Physical detail without cinematic exaggeration.", use_when="Use for foley, documentary and natural ambience.", models=S),
    _item("sfx.realism.enhanced", "sfx_realism", "Enhanced", "realistic sound with subtle designed enhancement",
          definition="The sound remains believable but has extra production weight.", audible="Clearer impact and polish than a raw recording.", use_when="Use for production-ready editorial effects.", models=S),
    _item("sfx.realism.designed", "sfx_realism", "Designed", "stylized cinematic sound design",
          definition="The sound may depart from strict physical realism.", audible="Layered, exaggerated or processed character.", use_when="Use for trailers, games and heightened moments.", models=S),
    _item("sfx.environment.dry_room", "sfx_environment", "Small dry room", "a small dry room",
          definition="A small interior with little reverberation.", audible="Short, controlled decay.", use_when="Use for close realistic foley.", models=S),
    _item("sfx.environment.church", "sfx_environment", "Large church interior", "a large reverberant church interior",
          definition="A large reflective sacred interior.", audible="Long reverberant tail and strong sense of scale.", use_when="Use for church doors, footsteps and ceremonial workspaces.", models=S),
    _item("sfx.environment.outdoors", "sfx_environment", "Outdoors", "an open outdoor environment",
          definition="An exterior with no enclosing room.", audible="Open sound with environmental air and distance.", use_when="Use for weather, nature and exterior action.", models=S),
    _item("sfx.environment.vehicle", "sfx_environment", "Vehicle interior", "inside a vehicle",
          definition="The listener is enclosed inside a vehicle.", audible="Exterior sound filtered by windows and body panels.", use_when="Use for rain, road and travel ambience.", models=S),
    _item("sfx.envelope.sharp", "sfx_envelope", "Sharp attack", "sharp attack",
          definition="The sound reaches peak level almost immediately.", audible="Crisp, precise transient.", use_when="Use for hits, clicks and snaps.", models=S),
    _item("sfx.envelope.fast_decay", "sfx_envelope", "Fast decay", "fast natural decay",
          definition="The sound fades quickly after its attack.", audible="Compact event with little tail.", use_when="Use for dry impacts and small objects.", models=S),
    _item("sfx.envelope.long_tail", "sfx_envelope", "Long tail", "long reverberant decay",
          definition="The sound continues fading for a long time.", audible="Workspace and resonance remain after the event.", use_when="Use for large rooms, impacts and designed transitions.", models=S),
    _item("sfx.character.natural", "sfx_character", "Natural", "natural",
          definition="Believable and physically grounded.", audible="Minimal stylisation or exaggeration.", use_when="Use for realistic scenes and foley.", models=S),
    _item("sfx.character.weighty", "sfx_character", "Weighty", "weighty with a strong low-mid body",
          definition="The sound should feel physically heavy.", audible="Strong low-mid body and substantial impact.", use_when="Use for large doors, objects and cinematic hits.", models=S),
    _item("sfx.character.soft", "sfx_character", "Soft", "soft and restrained",
          definition="The sound has limited force and sharpness.", audible="Gentle transient and controlled level.", use_when="Use for quiet handling and intimate scenes.", models=S),
    _item("sfx.character.gritty", "sfx_character", "Gritty", "gritty textured character",
          definition="Rough, dirty or abrasive detail.", audible="More noise, friction and irregularity.", use_when="Use for machinery, worn objects and aggressive design.", models=S),
    _item("sfx.processing.analog", "sfx_processing", "Analog saturation", "subtle analog saturation",
          definition="Gentle harmonic colour inspired by analog equipment.", audible="Slight warmth and density without obvious distortion.", use_when="Use to add body to realistic or designed effects.", models=S),
    _item("sfx.processing.distorted", "sfx_processing", "Distorted", "controlled distortion",
          definition="Intentional nonlinear roughness.", audible="Aggressive harmonics and compression.", use_when="Use for designed impacts or damaged machinery.", models=S),
    _item("sfx.behaviour.continuous", "sfx_behaviour", "Continuous ambience", "continuous ambience with subtle natural variation",
          definition="The sound continues for the entire requested duration.", audible="No single dominant event or abrupt finish.", use_when="Use for rain, rooms, crowds and environmental beds.", models=S),
    _item("sfx.behaviour.one_shot", "sfx_behaviour", "One-shot", "a single discrete event",
          definition="One event happens once.", audible="Clear start, event and decay.", use_when="Use for impacts, doors and interface sounds.", models=S),
)


TAXONOMY = {
    "version": TAXONOMY_VERSION,
    "items": list(ITEMS),
}


INDEX = {item["id"]: item for item in ITEMS}
