"""Small cached waveform summaries generated by FFmpeg on the server."""

from __future__ import annotations

import json
from pathlib import Path
import subprocess
from tempfile import NamedTemporaryFile

from origins.infrastructure.media_paths import media_root

CANONICAL_BARS = 4096


def _read_cache(path: Path, count: int, source: Path) -> list[float] | None:
    if not path.is_file() or path.stat().st_mtime < source.stat().st_mtime:
        return None
    try:
        values = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(values, list) and len(values) == count:
            return [float(value) for value in values]
    except (OSError, ValueError, TypeError):
        return None
    return None


def _write_cache(path: Path, values: list[float]) -> None:
    temporary: Path | None = None
    try:
        with NamedTemporaryFile(
                mode="w", encoding="utf-8", dir=path.parent,
                prefix=f".{path.name}.", suffix=".tmp",
                delete=False) as handle:
            json.dump(values, handle)
            temporary = Path(handle.name)
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def _downsample(values: list[float], count: int) -> list[float]:
    if count == len(values):
        return values
    result: list[float] = []
    for index in range(count):
        start = index * len(values) // count
        end = max(start + 1, (index + 1) * len(values) // count)
        result.append(round(max(values[start:end], default=0), 4))
    return result


def peaks(filename: str, bars: int) -> list[float]:
    root = media_root().resolve()
    source = (root / Path(filename).name).resolve()
    if source.parent != root or not source.is_file():
        raise LookupError("That audio file is unavailable.")
    return peaks_for_path(source, bars)


def peaks_for_path(source: Path, bars: int) -> list[float]:
    """Build the same bounded cache for any already-contained audio source."""
    source = source.resolve()
    if not source.is_file():
        raise LookupError("That audio file is unavailable.")
    count = max(8, min(4096, int(bars)))
    cache_root = source.parent
    cache = cache_root / f".{source.name}.peaks-v2-{count}.json"
    cached = _read_cache(cache, count, source)
    if cached is not None:
        return cached
    canonical_cache = cache_root / f".{source.name}.peaks-v2-{CANONICAL_BARS}.json"
    canonical = _read_cache(canonical_cache, CANONICAL_BARS, source)
    if canonical is not None:
        result = _downsample(canonical, count)
        _write_cache(cache, result)
        return result
    try:
        done = subprocess.run(
            ["ffmpeg", "-nostdin", "-loglevel", "error", "-i", str(source),
             "-vn", "-ac", "1", "-ar", "8000", "-f", "s16le", "pipe:1"],
            capture_output=True,
        )
    except OSError as exc:
        raise RuntimeError("The waveform could not be prepared.") from exc
    if done.returncode or not done.stdout:
        raise RuntimeError("The waveform could not be prepared.")
    samples = memoryview(done.stdout).cast("h")
    stride = max(1, len(samples) // CANONICAL_BARS)
    raw = []
    for index in range(CANONICAL_BARS):
        start = index * stride
        end = (len(samples) if index == CANONICAL_BARS - 1 else
               min(len(samples), start + stride))
        raw.append(max((abs(value) for value in samples[start:end]), default=0))
    maximum = max(raw, default=1) or 1
    canonical = [round(value / maximum, 4) for value in raw]
    _write_cache(canonical_cache, canonical)
    result = _downsample(canonical, count)
    _write_cache(cache, result)
    return result
