"""Small cached waveform summaries generated by FFmpeg on the server."""

from __future__ import annotations

import json
from pathlib import Path
import subprocess

from audio_studio.infrastructure.media_paths import media_root


def peaks(filename: str, bars: int) -> list[float]:
    root = media_root().resolve()
    source = (root / Path(filename).name).resolve()
    if source.parent != root or not source.is_file():
        raise LookupError("That audio file is unavailable.")
    count = max(8, min(512, int(bars)))
    cache = root / f".{source.name}.peaks-{count}.json"
    if cache.is_file() and cache.stat().st_mtime >= source.stat().st_mtime:
        try:
            values = json.loads(cache.read_text(encoding="utf-8"))
            if isinstance(values, list) and len(values) == count:
                return [float(value) for value in values]
        except (OSError, ValueError, TypeError):
            pass
    try:
        done = subprocess.run(
            ["ffmpeg", "-nostdin", "-loglevel", "error", "-i", str(source),
             "-vn", "-ac", "1", "-ar", "8000", "-f", "s16le", "pipe:1"],
            capture_output=True,
        )
    except OSError as exc:
        raise RuntimeError("The waveform could not be prepared.") from exc
    if done.returncode or not done.stdout:
        raise RuntimeError("The waveform could not be prepared.")
    samples = memoryview(done.stdout).cast("h")
    stride = max(1, len(samples) // count)
    raw = []
    for index in range(count):
        start = index * stride
        end = len(samples) if index == count - 1 else min(len(samples), start + stride)
        raw.append(max((abs(value) for value in samples[start:end]), default=0))
    maximum = max(raw, default=1) or 1
    result = [round(max(.08, value / maximum), 4) for value in raw]
    temporary = cache.with_suffix(cache.suffix + ".tmp")
    temporary.write_text(json.dumps(result), encoding="utf-8")
    temporary.replace(cache)
    return result
